// Product categories (product type) – align with Product model
export const PRODUCT_CATEGORIES = [
  'Smartphones',
  'Laptops',
  'Tablets',
  'Smart Watches',
  'Headphones & Earbuds',
  'Speakers',
  'Gaming Consoles',
  'TVs & Monitors',
  'Cameras',
  'Accessories',
  'Power Banks',
  'Chargers & Cables',
  'Phone Cases',
  'Screen Protectors',
  'Memory Cards',
  'USB Drives',
  'Computer Accessories',
  'Networking Equipment',
  'Smart Home Devices',
  'Wearables',
  'Audio Equipment',
  'Gaming Accessories',
  'Printers & Scanners',
  'Storage Devices',
  'Other'
];

// Product brands – align with Product model; include popular and new brands
export const PRODUCT_BRANDS = [
  'Apple',
  'Samsung',
  'Google',
  'Google Pixel',
  'Tecno',
  'Infinix',
  'Huawei',
  'Xiaomi',
  'Oppo',
  'Vivo',
  'Realme',
  'OnePlus',
  'Nokia',
  'Motorola',
  'LG',
  'Sony',
  'HP',
  'Dell',
  'Lenovo',
  'Asus',
  'Acer',
  'Microsoft',
  'Canon',
  'Nikon',
  'JBL',
  'Bose',
  'Beats',
  'Custom' // Allow custom brand entry
];
